### PR TITLE
prevent-errors-in-tests-since-the-table-is-in-History-Mode

### PR DESCRIPTION
**Pull request by xhulianpapa**
**Xhulian Papa - Dalfilo GmbH**

**Link the issue/feature request which this PR is meant to address**

**It prevents errors in the stg_google_ads__campaign history model since it has duplicates otherwise*

**How did you validate the changes introduced within this PR?**
Run tests in bigquery
**Which warehouse did you use to develop these changes?**
bigquery
**Did you update the CHANGELOG?**

- [ ] Yes

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)**

- [ ] Yes

**Provide an emoji that best describes your current mood**
 
:dancer:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

**PR Template** 
- [Community Pull Request Template](?expand=1&template=pull_request_template.md) (default)

- [Maintainer Pull Request Template](?expand=1&template=maintainer_pull_request_template.md) (to be used by maintainers)

Taken over by https://github.com/fivetran/dbt_google_ads_source/pull/41

### CODE REVIEW

**Comment by fivetran-joemarkiewicz** [comment]
Hi @xhulianpapa thanks for opening this PR! I would like to understand your update a bit more. My understanding is that the history model columns should not affect that underlying data that is already in the source table for these metadata tables. 

We should already address this type of issue within the [stg_google_ads_campaign_history](https://github.com/fivetran/dbt_google_ads_source/blob/d673ef9b8897c238dd05de8872b138231300d21b/models/stg_google_ads__campaign_history.sql#L37) model by including an `is_most_recent_record` boolean and a [test on the staging mode](https://github.com/fivetran/dbt_google_ads_source/blob/d673ef9b8897c238dd05de8872b138231300d21b/models/stg_google_ads.yml#L149-L152)l based on the `id` and the `updated_at` fields. 

Based on the above, I feel the non active duplicate records should be identifiable for the staging models. These are then filtered out in the transformation models. Let me know if this does address your initial question, or if you are looking to address a different issue.

**Comment by kaogilvie** [comment]
Hi @fivetran-joemarkiewicz -- I came across this issue because I'm having the same issues as @xhulianpapa , albeit my issues are now in multiple history tables. For whatever reason, the uniqueness tests are failing, as there are rows in the temp tables with the same primary keys & updated_at timestamps.

I'm using Snowflake, and can confirm that @xhulianpapa 's edits to the campaign temp table tests allows this model to succeed again. I'm going to be adding these edits to the ad_group_criterion_history, ad_group_history & ad_history uniqueness tests as well and would be happy to commit them into this PR, should it be deemed helpful / pass muster.

**Comment by fivetran-jamie** [comment]
Thanks so much for opening this @xhulianpapa! 

So I've gone ahead and made the changes in a separate branch, as @kaogilvie is correct that the other history tables are also seeing duplicates. Moreover, there are a few folks who don't yet have this `_fivetran_active` field, so I incorporated the code changes in a way that will not fail in these cases. Essentially, I added `_fivetran_active` to the `get_<history table>_columns()` macros, which create a null version of the column in the staging models if it is not found in the source tables. Then i filtered by `where coalesce(_fivetran_active, true)` in the final CTEs of the staging models

if y'all could test out the following branch, we can get it out and released ASAP
```yml
# packages.yml
packages:
  - git: https://github.com/fivetran/dbt_google_ads_source.git
    revision: prevent-errors-history-mode-tables
    warn-unpinned: false
```

**Comment by kaogilvie** [comment]
@fivetran-jamie this branch succeeds when I build with it. Thanks for the work on this!

**Comment by fivetran-jamie** [comment]
@kaogilvie wahoo! i'll go ahead and open a PR for that branch. I'll keep this one open until that one is merged, but will just close/not merge this one due to merge conflicts

**Comment by fivetran-jamie** [comment]
Ok just merged in https://github.com/fivetran/dbt_google_ads_source/pull/41, which extends the changes initially proposed here, so I will close this PR out

Currently releasing in v0.9.3 of the package!

**Pull request closed without merging**
